import 'package:hive/hive.dart';

part 'user_preferences.g.dart'; // This will be generated by build_runner

@HiveType(typeId: 0)
class UserPreferences extends HiveObject { // Extend HiveObject for easier box management
  @HiveField(0)
  String themeModeName; // e.g., "system", "light", "dark"

  @HiveField(1)
  bool rssNotificationsEnabled;

  @HiveField(2)
  int rssRefreshFrequencyHours;

  UserPreferences({
    required this.themeModeName,
    this.rssNotificationsEnabled = true, // Default to true
    this.rssRefreshFrequencyHours = 6, // Default to 6 hours
  });

  // Default preferences
  factory UserPreferences.defaults() {
    return UserPreferences(
      themeModeName: 'system',
      rssNotificationsEnabled: true,
      rssRefreshFrequencyHours: 6,
    );
  }
}
