name: Android Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Flutter Android APK (Release)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter version check
        run: flutter --version

      - name: Get Flutter dependencies
        working-directory: ./flutter_dashboard_app
        run: flutter pub get

      - name: Create keystore.properties
        working-directory: ./flutter_dashboard_app/android/app
        # run: |
        #   echo "storeFile=my-release-key.keystore" > keystore.properties
        #   echo "storePassword=${{ secrets.RELEASE_STORE_PASSWORD }}" >> keystore.properties
        #   echo "keyAlias=${{ secrets.RELEASE_KEY_ALIAS }}" >> keystore.properties
        #   echo "keyPassword=${{ secrets.RELEASE_KEY_PASSWORD }}" >> keystore.properties

      - name: Decode Keystore
        working-directory: ./flutter_dashboard_app/android/app
        # run: echo "${{ secrets.RELEASE_STORE_FILE_BASE64 }}" | base64 --decode > my-release-key.keystore

      - name: Build APK (release)
        working-directory: ./flutter_dashboard_app
        run: flutter build apk --release --verbose 2>&1
        timeout-minutes: 30

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: flutter_dashboard_app/build/app/outputs/flutter-apk/app-release.apk
