name: Android Build Minimal Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test_job:
    name: Test Job Execution
    runs-on: ubuntu-latest
    steps:
      - name: Run a test command
        run: echo "Test job is running successfully!"
