name: Android Build

on:
  push:
    branches: [stable_main]
  pull_request:
    branches: [stable_main]
  workflow_dispatch:

jobs:
  build_android_release:
    name: Build Flutter Android APK (Release)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./flutter_dashboard_app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter clean
        run: flutter clean

      - name: Upgrade dependencies
        run: flutter pub upgrade --major-versions

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Generate files (build_runner)
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Set Gradle version
        working-directory: ./flutter_dashboard_app/android
        run: ./gradlew wrapper --gradle-version 8.9 --distribution-type all

      - name: Decode Keystore and Create keystore.properties
        if: ${{ secrets.RELEASE_STORE_FILE_BASE64 && secrets.RELEASE_STORE_PASSWORD && secrets.RELEASE_KEY_ALIAS && secrets.RELEASE_KEY_PASSWORD }}
        working-directory: ./flutter_dashboard_app/android
        run: |
          echo "${{ secrets.RELEASE_STORE_FILE_BASE64 }}" | base64 --decode > my-release-key.keystore
          cat <<EOF > keystore.properties
          storeFile=my-release-key.keystore
          storePassword=${{ secrets.RELEASE_STORE_PASSWORD }}
          keyAlias=${{ secrets.RELEASE_KEY_ALIAS }}
          keyPassword=${{ secrets.RELEASE_KEY_PASSWORD }}
          EOF

      - name: Build APK (Release)
        run: flutter build apk --release --verbose
        timeout-minutes: 30

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: flutter_dashboard_app/build/app/outputs/flutter-apk/app-release.apk